# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- powershell: New-AzureRmResourceGroupDeployment -ResourceGroupName "myresourcegroup01" -name "mydatalakestore02" -TemplateUri "https://raw.githubusercontent.com/viraldedai23/myRepository01/master/datalakestore.json" -TemplateParameterUri "https://raw.githubusercontent.com/viraldedai23/myRepository01/master/datalakestore_parameter.json"